# Perceptron

Implemente o Perceptron para classificar o dataset Iris, separando as classes “setosa” e “versicolor”.

In [58]:
import numpy as np
import pandas as pd

In [59]:
#Load the dataset
from sklearn.datasets import load_iris
iris = load_iris()
X = iris['data']
Y = iris['target']

#Separando setosa e versicolor
x = X[(Y==0)|(Y==1)]
y = Y[(Y==0)|(Y==1)]

#Mudando os valores de y para implementar o perceptron
y = np.where(y == 0, 1, -1)

In [69]:
#Função para predição da saída
def predict(x,w,b):
    #print((np.dot(x, w) + b))
    return np.where((np.dot(x, w) + b)>= 0, 1, -1)

#Setup dos valores inicias
w=np.zeros(x.shape[1])
b=0
learning_rate=0.1

#Primeira predição
p1=predict(x,w,b)

#Contagem de erros
erro=0
for i in range(len(p1)):
    if p1[i]!=y[i]:
        erro=erro+1
print('Quantity of worng predictions:',erro)

for i in range(len(y)):
    w = (y[i]-predict(x,w,b)[i])*x[i]*learning_rate + w 
    #print(w)
    
for i in range(len(y)):
    w = (y[i]-predict(x,w,b)[i])*x[i]*learning_rate + w 
    #print(w)
    
for i in range(len(y)):
    w = (y[i]-predict(x,w,b)[i])*x[i]*learning_rate + w 
    print(w)
    
for i in range(len(y)):
    w = (y[i]-predict(x,w,b)[i])*x[i]*learning_rate + w 
    print(w)



#Segunda predição
p2=predict(x,w,b)
print(p2)


#Contagem de erros
erro=0
for i in range(len(p2)):
    if p2[i]!=y[i]:
        erro=erro+1
print('Quantity of worng predictions:',erro)

Quantity of worng predictions: 50
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.22  0.72 -1.04 -0.44]
[ 0.

In [87]:
#Função para predição da saída
def predict(x,w,b):
    #print((np.dot(x, w) + b))
    return np.where((np.dot(x, w) + b)>= 0, 1, -1)

#Setup dos valores inicias
w=np.zeros(x.shape[1])
b=0
learning_rate=0.1

#Primeira predição
p1=predict(x,w,b)
print('\nOutput without weight:\n',p1)

#Contagem de erros
erro=0
for i in range(len(p1)):
    if p1[i]!=y[i]:
        erro=erro+1
print('\nQuantity of worng predictions:',erro)

#Atualização do peso - loop se repete até que a quantidade de erros seja nula
while(erro!=0):
    for i in range(len(y)):
        w = (y[i]-predict(x,w,b)[i])*x[i]*learning_rate + w 
        #print(w)
    erro=0
    for i in range(len(p1)):
        if predict(x,w,b)[i]!=y[i]:
            erro=erro+1    
            
#Segunda predição
p2=predict(x,w,b)
print('\n\nOutput after weight implementation:\n',p2)


#Contagem de erros
erro=0
for i in range(len(p2)):
    if p2[i]!=y[i]:
        erro=erro+1
print('\nQuantity of worng predictions:',erro)


Output without weight:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Quantity of worng predictions: 50


Output after weight implementation:
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1]

Quantity of worng predictions: 0
